# Generated by Django 5.1.7 on 2025-03-29 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='community',
            field=models.ForeignKey(blank=True, help_text='The primary community this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='communities.community'),
        ),
    ]
