# Generated by Django 5.1.7 on 2025-03-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_s3_key',
            field=models.CharField(blank=True, help_text='S3 object key for the profile picture', max_length=1024, null=True),
        ),
    ]
