# Generated by Django 5.1.7 on 2025-04-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_profile_picture_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo_s3_key',
            field=models.CharField(blank=True, help_text='S3 object key for the cover photo', max_length=1024, null=True),
        ),
    ]
