# Generated by Django 5.1.7 on 2025-04-27 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_average_rating_userprofile_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='average_rating',
            field=models.FloatField(default=3.0, help_text='Average rating received by the user (0-5)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
