# Generated by Django 5.1.7 on 2025-03-29 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official or commonly known name (e.g., Prestige Shantiniketan)', max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Approximate center latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Approximate center longitude', max_digits=10, null=True)),
                ('is_approved', models.BooleanField(db_index=True, default=True, help_text='Has this community been approved by admin?')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this community currently active/visble?')),
                ('is_officially_verified', models.BooleanField(default=False, help_text='Represents formal verification/partnership with management/RWA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'ordering': ['city', 'name'],
                'unique_together': {('name', 'city', 'pincode')},
            },
        ),
        migrations.CreateModel(
            name='CommunitySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_name', models.CharField(help_text='Name suggested by the user', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved (Community Created)'), ('REJECTED_DUPLICATE', 'Rejected - Duplicate'), ('REJECTED_INVALID', 'Rejected - Invalid/Spam'), ('MERGED', 'Merged with Existing')], db_index=True, default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin during review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_community', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_source', to='communities.community')),
                ('suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
