# Generated by Django 5.1.7 on 2025-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the community (e.g., location, features)'),
        ),
        migrations.AddField(
            model_name='communitysuggestion',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the community (e.g., location, features)'),
        ),
    ]
