# Generated by Django 5.1.7 on 2025-04-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitysuggestion',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Approximate center latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='communitysuggestion',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Approximate center longitude', max_digits=10, null=True),
        ),
    ]
