# Generated by Django 5.1.7 on 2025-03-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Currently Booked'), ('BORROWED', 'Currently Borrowed'), ('UNAVAILABLE', 'Temporarily Unavailable')], db_index=True, default='AVAILABLE', max_length=15),
        ),
    ]
