# Generated by Django 5.1.7 on 2025-03-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_alter_item_availability_status'),
        ('transactions', '0002_remove_review_id_and_more'),
        ('users', '0003_userprofile_profile_picture_s3_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The main content/text of the notification.')),
                ('notification_type', models.CharField(choices=[('REQ_REC', 'New Borrow Request Received'), ('REQ_ACC', 'Request Accepted'), ('REQ_DEC', 'Request Declined'), ('REQ_CAN_BOR', 'Request Cancelled by Borrower'), ('REQ_CAN_LEN', 'Request Cancelled by Lender'), ('PICKUP_CONF', 'Item Pickup Confirmed'), ('RET_CONF_BOR', 'Item Return Initiated'), ('REQ_COMP', 'Borrowing Completed'), ('REV_REC', 'New Review Received'), ('REV_PROMPT', 'Reminder to Leave Review'), ('COM_SUG_APP', 'Community Suggestion Approved'), ('COM_SUG_REJ', 'Community Suggestion Rejected'), ('NEW_MSG', 'New Message Received'), ('GEN_INFO', 'Information')], db_index=True, help_text='Categorizes the notification for display or handling.', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Has the recipient marked this notification as read?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the notification was created.')),
                ('actor', models.ForeignKey(blank=True, help_text='The user profile who performed the action causing the notification (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to='users.userprofile')),
                ('recipient', models.ForeignKey(help_text='The user profile receiving the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile')),
                ('related_item', models.ForeignKey(blank=True, help_text='Link to the relevant Item, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('related_request', models.ForeignKey(blank=True, help_text='Link to the relevant Borrowing Request, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.borrowingrequest')),
                ('related_user_profile', models.ForeignKey(blank=True, help_text='Link to another User Profile relevant to the notification (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
